server:
  port: 8040
spring:
  application:
    name: microservice-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:8761/eureka/ ,http://eureka2:8762/eureka/
  instance:
    prefer-ip-address: true
management:
  security:
    enabled: false

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000         #用于解决上传大文件时超时问题
        timeout:
          enabled: false
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000                             #设置超时时间，用于解决上传大文件超时问题
